{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: asyncio-helpers
  version: {{ GIT_VERSION }}

build:
  entry_points:
    - trollius-to-async = asyncio_helpers.trollius_to_async:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip

  run:
    - logging-helpers
    - trollius  # [py<34]

test:
  imports:
    - asyncio_helpers

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
